<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="<?php echo strtolower(SUF_VERSION); ?>" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="<?php echo strtolower(SUF_VERSION); ?>" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="<?php echo strtolower(SUF_VERSION); ?>" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="<?php echo strtolower(SUF_VERSION); ?>" class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="UTF-8" />
        <meta name="language" content="<?php echo strtolower(SUF_VERSION); ?>" />
        <base href="<?php echo $this->url; ?>" />

        <?php echo $this->css; ?>
        <script type="text/javascript">window.jQuery || document.write('<script type="text/javascript" src="app/front/js/jquery/jquery-1.7.min.js"><\/script>')</script>
        <!--[if IE]>
            <script src="js/html5.js"></script>
        <![endif]-->
        <?php echo $this->javascript; ?>



    </head>
    <body>

        <div class="navbar navbar-fixed-top back-toolbar">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a href="" class="brand">Outils de l'administrateur</a>




                    <ul class="nav pull-right">
                        <li><a class="" href="javascript:toggleMercury()" target="_parent">Éditer</a></li>
                        <li>
                            <?php
                            if (isset($this->page) && is_object($this->page)) {
                                ?>
                                <?php
                                if ($this->page->getMeta("visible") == 1) {
                                    ?>
                                    <a><span class="label label-success">Visible</span></a>
                                    <?php
                                } else {
                                    ?>
                                    <a><span class="label label-warning">Non visible</span></a>
                                    <?php
                                }
                                ?>
                                <?php
                            }
                            ?></li>
                        <li class="divider-vertical"></li>
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Mode <?php echo $this->modePrevisualisation ? 'Prévisualisation' : 'Normal' ?>  <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="?mode_previsualisation=0">Normal</a></li>
                                <li><a href="?mode_previsualisation=1">Prévisualisation</a></li>
                            </ul>
                        </li>
                        <li class="divider-vertical"></li>
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#"><?php echo $this->utilisateurAdmin->get("nom"); ?> <?php echo $this->utilisateurAdmin->get("prenom"); ?> <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="back/sign/signout.html"><b>Déconnexion</b></a></li>
                            </ul>
                        </li>
                    </ul>

                </div>

            </div>
        </div>

    </body>
</html>
