<style>body { padding-top: 40px; }</style>


<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a href="" class="brand"><img src="app/back/img/gray_dark/home_16x16.png"> <?php echo $this->site; ?></a>




            <ul class="nav pull-right">
                <li><a class="" href="javascript:toggleMercury()" target="_parent">Éditer</a></li>
                <li>
                    <?php
                    if (isset($this->page) && is_object($this->page)) {
                        ?>
                        <?php
                        if ($this->page->getMeta("visible") == 1) {
                            ?>
                            <a><span class="label label-success">Visible</span></a>
                            <?php
                        } else {
                            ?>
                            <a><span class="label label-info">Pas visible</span></a>
                            <?php
                        }
                        ?>
                        <?php
                    }
                    ?></li>
                <li class="divider-vertical"></li>
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">Mode <?php echo $this->modePrevisualisation ? 'Prévisualisation' : 'Normal' ?>  <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="?mode_previsualisation=0">Normal</a></li>
                        <li><a href="?mode_previsualisation=1">Prévisualisation</a></li>
                    </ul>
                </li>
                <li class="divider-vertical"></li>
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#"><?php echo $this->utilisateurAdmin->get("nom"); ?> <?php echo $this->utilisateurAdmin->get("prenom"); ?> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="back/sign/signout.html"><b>Déconnexion</b></a></li>
                    </ul>
                </li>
            </ul>

        </div>

    </div>
</div>

<?php $this->add("../../back/view/template/cropdialog.phtml"); ?>
<script src="app/back/js/jquery/jquery-ui-1.8.23.custom.min.js" type="text/javascript"></script>


<script type="text/javascript">
    var head = document.getElementsByTagName("head")[0];

    function loadSelectImages(element) {
        $.get("back/media/autocomplete.html?id_gab_page=<?php echo $this->page->getMeta("id") ?>", function(data) {
                    $selectImage = $(element).find(".media_image_list")
                    $selectImage.empty().append('<option></option>');
                    $.each(data, function(id, item) {
                        var beforeLastSlash = item.path.lastIndexOf("/", item.path.lastIndexOf("/")-1)+1
                        $selectImage.append('<option value="' + item.path.substr(beforeLastSlash)  + '">' + item.label + ' (' + item.size + ')</option>');
                    })

                    $selectImage.bind("change", function() {
                        var value  = $(this).val()
                        $selectImage.parents("form:first").find("#media_image_url").val(value)
                    })

                }, "json")
    }
    function loadCss(src) {
        var link = document.createElement('link');
          link.href = src;
          link.media = 'screen';
          link.rel = 'stylesheet';
          link.type = 'text/css';
          head.appendChild(link);
        }
function loadScript(src) {
          var script = document.createElement('script');
          script.src = src;
          script.type = 'text/javascript';
          script.charset = 'utf-8';
          head.appendChild(script);
          script.onload = function() {
              document.body.style.visibility = 'visible';
              document.body.style.display = 'block';

          };
        }
    $(function() {






        $(document).bind('DOMNodeInserted', function(e) {
            var element = e.target;
            if ($(element).attr("id") == "mercury_media" && $(element).find(".media_image_list").length == 1) {
                loadSelectImages(element)

            }

            if ($(element).attr("id") == "mercury_link" && $(element).find(".media_link_list").length == 1) {
                $.get("sitemap.xml?json=1&visible=0&term=", function(data) {
                    $selectLink = $(element).find(".media_link_list")
                    $selectLink.empty().append('<option></option>');
                    $.each(data, function(id, item) {
                        $selectLink.append('<option value="' + item.path  + '">' + item.title + '</option>');
                    })

                    $selectLink.bind("change", function() {
                        var value  = $(this).val()
                        $selectLink.parents("form:first").find("#link_external_url").val(value)
                    })

                }, "json")

            }


        });
    });

    window.mercuryPackages = {
        development: {javascripts: 'mercury.js', stylesheets: 'mercury.css'},
        bundled: {javascripts: 'mercury.js,mercury_dialogs.js', stylesheets: '../../css/mercury/mercury.bundle.css'}
    };
    jQuery(window).on('mercury:ready', function() {
        // do whatever additional loading that should happen here
        // you can also make simple changes to default functionality here

    });




    function toggleMercury() {
        if (typeof(Mercury) == 'undefined') {
            alert("Sorry, but Mercury Editor isn't supported by your current browser.\n\nBrowsers that support the required HTML5 spec:\n\n  Chrome 10+\n  Firefox 4+\n  Safari 5+\n  Opera 11.64+\n  Mobile Safari (iOS 5+)");
        } else {
            Mercury.trigger('toggle:interface');
            Mercury.config.uploading = {
                enabled: true,
                allowedMimeTypes: ['image/jpeg', 'image/gif', 'image/png'],
                maxFileSize: 1235242880,
                inputName: 'file',
                url: '<?php echo $this->url; ?>back/media/upload.html?id_gab_page=<?php echo $this->page->getMeta("id") ?>;',
                handler: false
            };
            Mercury.PageEditor.prototype.save = function() {
                var data = this.serialize();
                data.id_gab_page = {value: <?php echo $this->page->getMeta("id") ?>};
                data.id_version = {value: <?php echo $this->page->getMeta("id_version") ?>};
                data.id_gabarit = {value: <?php echo $this->page->getMeta("id_gabarit") ?>};
                data.id_api = {value: <?php echo $this->page->getMeta("id_api") ?>};
                var lightview = Mercury.lightview(null, {title: 'Enregistrement en cours, veuillez patientez ...', closeButton: true});
                setTimeout(function() {
                    $.post('<?php echo $this->url; ?>back/page/save.html?edit-front=1', {content: top.JSON.stringify(data, null)}, function() {
                        lightview.loadContent('<div style="width:500px">La page a été enregistrée avec succès</div>');
                        javascript:toggleMercury()
                    });
                }, 500);
            }

//        loadScript("back/js/jquery/jquery-1.8.0.min.js")
        loadScript("app/back/js/jquery/jquery-ui-1.8.23.custom.min.js")
        loadScript("app/back/js/bootstrap/bootstrap.min.js")
        loadScript("app/back/js/jquery/jcrop/jquery.Jcrop.min.js")
        loadScript("app/back/js/jquery/ui.spinner.min.js")
        loadScript("app/back/js/crop_front.js")

        loadCss("app/back/css/jcrop/jquery.Jcrop.min.css")
        loadCss("app/back/css/jquery-ui-1.8.7.custom.css")
        loadCss("app/back/css/bootstrap/bootstrap-responsive.min.css")
        loadCss("app/back/css/bootstrap/bootstrap.min.css")
        loadCss("app/back/css/ui.spinner.css")
        loadCss("app/back/css/crop.css")

        cloneModalCrop.appendTo("body")
        }
    }
</script>
<script>
    var cloneModalCrop = $('#modalCrop').clone()
    jQuery(parent).trigger('initialize:frame');
</script>

